package model

import kotlinx.serialization.Serializable

@Serializable
data class Data(
    val app_temp: Float,
    val aqi: Int,
    val city_name: String,
    val clouds: Int,
    val country_code: String,
    val datetime: String,
    val dewpt: Float,
    val dhi: Float,
    val dni: Float,
    val elev_angle: Float,
    val ghi: Float,
    val gust: Float? = null,
    val h_angle: Float,
    val lat: Float,
    val lon: Float,
    val ob_time: String,
    val pod: String,
    val precip: Float,
    val pres: Float,
    val rh: Int,
    val slp: Float,
    val snow: Int,
    val solar_rad: Float,
    val sources: List<String>,
    val state_code: String,
    val station: String,
    val sunrise: String,
    val sunset: String,
    val temp: Float,
    val timezone: String,
    val ts: Long,
    val uv: Float,
    val vis: Float,
    val weather: Weather,
    val wind_cdir: String,
    val wind_cdir_full: String,
    val wind_dir: Int,
    val wind_spd: Float
)
